title: "OK Transformer"  
author: ğ—½ğ—®ğ—¿ğ˜ğ—¶ğ—°ğ—¹ğ—²ğŸ­ğŸ¯ğŸ¯ğŸ­. Powered by <a href="https://jupyterbook.org">Jupyter Book</a>.
logo: logo.png

only_build_toc_files: true

execute:
  execute_notebooks: 'off'

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib

launch_buttons:
  binderhub_url: ""
  
repository:
  url: https://github.com/particle1331/ok-transformer
  path_to_book: docs  # Path to book relative to repository root
  branch: master      # Branch of repo to use when creating links

html:
  home_page_in_navbar: false
  use_issues_button: true
  use_repository_button: true
  extra_navbar: ""
  favicon: "favicon.png"

sphinx:
  default_dark_mode: true
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
