title: "ğ—œğ—»ğ—²ğ—³ğ—³ğ—¶ğ—°ğ—¶ğ—²ğ—»ğ˜ ğ—¡ğ—²ğ˜ğ˜„ğ—¼ğ—¿ğ—¸ğ˜€"
author: ğ—¥ğ—¼ğ—» ğ— ğ—²ğ—±ğ—¶ğ—»ğ—®. Powered by <a href="https://jupyterbook.org">Jupyter Book</a>.
logo: img/pone.0237978.g001.png

execute:
  execute_notebooks: 'off'

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/particle1331/inefficient-networks
  path_to_book: docs  # Path to book relative to repository root
  branch: master      # Branch of repo to use when creating links

html:
  home_page_in_navbar: false
  use_issues_button: true
  use_repository_button: true
  extra_navbar: ""
  favicon: "img/pone.0237978.g001.png"

sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
